### ISSUE TITLE
Integrating into Companion

### ISSUE THREAD

**Issue by ectoplasmosis** [bitfocus/companion-module-livemind-recorder#1]
Hey, many thanks for creating this module.

I've just bought a copy of Livemind Recorder and wish to use it with Companion, but cannot find this module in either the release or beta versions.

How could I integrate it into a working Companion install?

Many thanks!

**Comment by ChgoChad** [comment]
Hello thanks for the note. I just finished developing the module and I'm waiting for the core developers to merge my code into the main repository which would make my module available in the public version.

In the meantime while I wait for that I can send you a custom build that includes the module.

Let me know.

__________________________________
Chad Carpenter | +1 312.772.4056

________________________________
From: ectoplasmosis ***@***.***>
Sent: Sunday, June 27, 2021 9:32:58 AM
To: bitfocus/companion-module-livemind-recorder ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bitfocus/companion-module-livemind-recorder] Integrating into Companion (#1)


Hey, many thanks for creating this module.

I've just bought a copy of Livemind Recorder and wish to use it with Companion, but cannot find this module in either the release or beta versions.

How could I integrate it into a working Companion install?

Many thanks!

**Comment by ectoplasmosis** [comment]
Hey, that would be incredible!

If you could email it, preferably a Windows version, to: avint *AT* iriswave.org 

...that would be very much appreciated. Thanks in advance!

**Comment by ChgoChad** [comment]
Hi ...Great, I will generate a full build later this evening and then send you a link to download.

I hope the module works well for you. I would appreciate any feedback that you have after using it.

__________________________________
Chad Carpenter | +1 312.772.4056

________________________________

**Comment by ChgoChad** [comment]
Email with link to custom build sent

**Comment by BenJamesAndo** [comment]
Hello, is there any news when this module will be included in a beta build? I'm also wanting to use it. I've never compiled software from source code so if you could email me a companion build as well that'd be awesome. benjamesando _AT_ gmail.com
Happy to give feedback on it as I'll be using it on a weekly basis.

**Comment by ChgoChad** [comment]
Hi Ben - Thanks for your message. I'm not sure when it will be included in a beta build.  I've requested for it to be included. I know the core dev team is backed up with requests--however it's probably time for me to remind them that this module needs to be included.  For the time being I will generate a fresh build for you that includes the module... that way you don't have to compile from source code.  I will email you a build at the address you gave above.

**Comment by ChgoChad** [comment]
Email with link to custom build sent
